<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
    <PackageReference Include="ToolSharp" Version="1.0.5" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

    <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Test</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Presentation</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="UseCases\Commands\Company\Update\" />
      <Folder Include="UseCases\Queries\" />
      <Folder Include="UseCases\Queries\Company\" />
      <Folder Include="UseCases\Queries\Company\GetOne\" />
      <Folder Include="UseCases\Queries\User\" />
      <Folder Include="UseCases\Queries\User\GetAll\" />
      <Folder Include="UseCases\Queries\User\GetOne\" />
    </ItemGroup>

  

</Project>
