// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20260629152651_AddChunksChatSessionsChatMessages")]
    partial class AddChunksChatSessionsChatMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasPostgresExtension("vector");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Core.Chat.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.HasIndex("ChatSessionId", "CreatedDate");

                    b.HasIndex("DeletedDate");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Core.Chat.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContextUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("ContextUserId");

                    b.HasIndex("DeletedDate");

                    b.ToTable("ChatSessions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Core.Documents.Chunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<int>("PositionIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("DeletedDate");

                    b.HasIndex("DocumentId");

                    b.ToTable("Chunks", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Core.Chat.ChatMessage", b =>
                {
                    b.HasOne("Domain.Entities.Core.Chat.ChatSession", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Core.Chat.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
