// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20260624174249_DropLegacyAuthTables")]
    partial class DropLegacyAuthTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Abstracts.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamptz");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamptz");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id")
                        .HasName("PK_Subscriptions");

                    b.ToTable("Subscriptions", null, t =>
                        {
                            t.Property("EndDate")
                                .HasColumnName("Subscription_EndDate");

                            t.Property("StartDate")
                                .HasColumnName("Subscription_StartDate");
                        });

                    b.HasDiscriminator<string>("SubscriptionType").HasValue("Subscription");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Core.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ChunksGenerated")
                        .HasColumnType("integer");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletionRequestedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("DeletionRequestedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EmbeddingCompletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("EmbeddingErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("EmbeddingProcessingStatus")
                        .HasColumnType("integer");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmbedding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("SignedUrlExpiration")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsEmbedding");

                    b.HasIndex("Status");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Core.Subscriptions.AccountSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamptz");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("PlanId");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id")
                        .HasName("PK_AccountSubscriptions");

                    b.ToTable("AccountSubscriptions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Payments.StripeWebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamptz");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("EventId");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("PayloadJson");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ReceivedAt");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Type");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id")
                        .HasName("PK_StripeWebhookEvents");

                    b.ToTable("StripeWebhookEvents", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Picture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContainerName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("ContainerName");

                    b.Property<string>("ContentType")
                        .HasColumnType("varchar")
                        .HasColumnName("ContentType");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<DateTime?>("SignedUrlExpiration")
                        .HasColumnType("timestamptz")
                        .HasColumnName("SignedUrlExpiration");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id")
                        .HasName("PK_Pictures");

                    b.ToTable("Pictures", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Payments.FreeSubscription", b =>
                {
                    b.HasBaseType("Domain.Entities.Abstracts.Subscription");

                    b.ToTable("Subscriptions", t =>
                        {
                            t.Property("EndDate")
                                .HasColumnName("Subscription_EndDate");

                            t.Property("StartDate")
                                .HasColumnName("Subscription_StartDate");
                        });

                    b.HasDiscriminator().HasValue("Free");
                });

            modelBuilder.Entity("Domain.Entities.Payments.PremiumSubscription", b =>
                {
                    b.HasBaseType("Domain.Entities.Abstracts.Subscription");

                    b.ToTable("Subscriptions", t =>
                        {
                            t.Property("EndDate")
                                .HasColumnName("Subscription_EndDate");

                            t.Property("StartDate")
                                .HasColumnName("Subscription_StartDate");
                        });

                    b.HasDiscriminator().HasValue("Premium");
                });

            modelBuilder.Entity("Domain.Entities.Abstracts.Subscription", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.PaymentDetails", "Payment", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PaymentGateway")
                                .HasMaxLength(50)
                                .HasColumnType("varchar")
                                .HasColumnName("PaymentProvider");

                            b1.Property<string>("TransactionId")
                                .HasColumnType("varchar")
                                .HasColumnName("TransactionId");

                            b1.HasKey("SubscriptionId");

                            b1.ToTable("Subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.OwnsOne("Domain.ValueObjects.SubscriptionPeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamptz")
                                .HasColumnName("EndDate");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamptz")
                                .HasColumnName("StartDate");

                            b1.HasKey("SubscriptionId");

                            b1.ToTable("Subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.Navigation("Payment");

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Core.Document", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.BigString", "CloudStorageKey", b1 =>
                        {
                            b1.Property<Guid>("DocumentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("CloudStorageKey");

                            b1.HasKey("DocumentId");

                            b1.ToTable("Documents");

                            b1.WithOwner()
                                .HasForeignKey("DocumentId");
                        });

                    b.OwnsOne("Domain.ValueObjects.BigString", "FileName", b1 =>
                        {
                            b1.Property<Guid>("DocumentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("FileName");

                            b1.HasKey("DocumentId");

                            b1.ToTable("Documents");

                            b1.WithOwner()
                                .HasForeignKey("DocumentId");
                        });

                    b.OwnsOne("Domain.ValueObjects.BigString", "LocalTemporaryPath", b1 =>
                        {
                            b1.Property<Guid>("DocumentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("LocalTemporaryPath");

                            b1.HasKey("DocumentId");

                            b1.ToTable("Documents");

                            b1.WithOwner()
                                .HasForeignKey("DocumentId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Url", "SignedUrl", b1 =>
                        {
                            b1.Property<Guid>("DocumentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Endereco")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("SignedUrl");

                            b1.HasKey("DocumentId");

                            b1.ToTable("Documents");

                            b1.WithOwner()
                                .HasForeignKey("DocumentId");
                        });

                    b.Navigation("CloudStorageKey");

                    b.Navigation("FileName")
                        .IsRequired();

                    b.Navigation("LocalTemporaryPath");

                    b.Navigation("SignedUrl");
                });

            modelBuilder.Entity("Domain.Entities.Core.Subscriptions.AccountSubscription", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.EntraUserId", "EntraUserId", b1 =>
                        {
                            b1.Property<Guid>("AccountSubscriptionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar")
                                .HasColumnName("EntraUserId");

                            b1.HasKey("AccountSubscriptionId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("IX_AccountSubscriptions_EntraUserId");

                            b1.ToTable("AccountSubscriptions");

                            b1.WithOwner()
                                .HasForeignKey("AccountSubscriptionId");
                        });

                    b.OwnsOne("Domain.ValueObjects.StripeCustomerId", "StripeCustomerId", b1 =>
                        {
                            b1.Property<Guid>("AccountSubscriptionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar")
                                .HasColumnName("StripeCustomerId");

                            b1.HasKey("AccountSubscriptionId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("IX_AccountSubscriptions_StripeCustomerId");

                            b1.ToTable("AccountSubscriptions");

                            b1.WithOwner()
                                .HasForeignKey("AccountSubscriptionId");
                        });

                    b.OwnsOne("Domain.ValueObjects.SubscriptionStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("AccountSubscriptionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar")
                                .HasColumnName("SubscriptionStatus");

                            b1.HasKey("AccountSubscriptionId");

                            b1.ToTable("AccountSubscriptions");

                            b1.WithOwner()
                                .HasForeignKey("AccountSubscriptionId");
                        });

                    b.Navigation("EntraUserId")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();

                    b.Navigation("StripeCustomerId")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Picture", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.BigString", "CloudStorageKey", b1 =>
                        {
                            b1.Property<Guid>("PictureId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar")
                                .HasColumnName("CloudStorageKey");

                            b1.HasKey("PictureId");

                            b1.ToTable("Pictures");

                            b1.WithOwner()
                                .HasForeignKey("PictureId");
                        });

                    b.OwnsOne("Domain.ValueObjects.BigString", "LocalTemporaryPath", b1 =>
                        {
                            b1.Property<Guid>("PictureId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar")
                                .HasColumnName("LocalTemporaryPath");

                            b1.HasKey("PictureId");

                            b1.ToTable("Pictures");

                            b1.WithOwner()
                                .HasForeignKey("PictureId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Url", "SignedUrl", b1 =>
                        {
                            b1.Property<Guid>("PictureId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Endereco")
                                .HasMaxLength(255)
                                .HasColumnType("varchar")
                                .HasColumnName("SignedUrl");

                            b1.HasKey("PictureId");

                            b1.ToTable("Pictures");

                            b1.WithOwner()
                                .HasForeignKey("PictureId");
                        });

                    b.Navigation("CloudStorageKey");

                    b.Navigation("LocalTemporaryPath");

                    b.Navigation("SignedUrl");
                });
#pragma warning restore 612, 618
        }
    }
}
