<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Agents\" />
    <Folder Include="Providers\" />
    <Folder Include="Providers\Abstractions\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Prompts\*.md" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
